### ISSUE TITLE
fix link to `dashboard` on `README.md`

### ISSUE THREAD

**Issue by davisokoth** [AfricasTalkingLtd/africastalking-ruby#22]
Link currently points to `account/africastalking...` instead of `account.africastalking...`

**Comment by calvinkarundu** [comment]
Hey Davis thanks for pointing that out, can you open a PR?

**Comment by davisokoth** [comment]
Alright, will do later on

**Comment by loisek** [comment]
@davisokoth, thank you for your contribution.
This has been merged into master.
Happy hacking!
