### ISSUE TITLE
USSD Getting Started is Missing in README

### ISSUE THREAD

**Issue by jmziya** [AfricasTalkingLtd/africastalking-ruby#5]
I have setup the sdk properly but I do not know how I can initiate the code to respond to my USSD requests. Can this be added in the README? I am kind of stuck. Or if there is anyone who can help with how I can do that.

**Comment by AnthonyLimo** [comment]
Hi man, so USSD doesn't rely on the SDK. All you need is your server running (exposed to the internet) and an Africa's Talking account. Check this repo out https://github.com/AnthonyLimo/AT-USSD to help you understand what to do.

**Comment by jmziya** [comment]
Hie @AnthonyLimo , I got it working. My issue meant, you know how the Africa'sTalking site has a clear PHP Code Sample. If it had something like that as well for the ruby it would help out alot with getting started.

Otherwise, I am all good now. My app is working properly. Took me longer than in PHP.

**Comment by AnthonyLimo** [comment]
Thanks for this! We will make sure to add more code samples onto our docs 😊

**Comment by jmziya** [comment]
Welcome @AnthonyLimo . Africa'sTalking is Best.!!!
